### ISSUE TITLE
Standard content in the app_offline.htm

### ISSUE THREAD

**Issue by Master-Silver** [sayedihashimi/sayed-samples#7]
Hey,

I followed the instructions from your [manual](http://sedodream.com/2012/01/08/HowToTakeYourWebAppOfflineDuringPublishing.aspx), and it works, but the content of the app_offline.htm is the standard content and is not replaced with the app_offline-template.htm content. I use Visual Studio 2019 Professional and deployed a .NET Framework 4.72 web app. Have you any idea why this is?

Thanks
Master Silver

**Comment by sayedihashimi** [comment]
Hi @Master-Silver please file an issue with the Visual Studio team, more info over at https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022.
